kind: pipeline
name: and_ci_cliente

steps:
- name: check_branch
  image: jjvargass/qa_develoment:latest
  commands:
  - python /app/check_branch.py -H ${DRONE_GIT_HTTP_URL}
  when:
    branch:
    - develop
    - release/*
    - devops
    event:
    - push

- name: run_sonar_scanner
  image: timbru31/java-node
  commands:
    - export RELEASE=4.2.0.1873
    - cat /etc/os-release
    - apt-get update -y
    - apt-get -y install curl grep sed unzip zip nodejs apt-utils
    - node --version
    - npm --version
    - curl --insecure -o ./sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$RELEASE-linux.zip
    - unzip sonarscanner.zip
    - rm sonarscanner.zip
    - rm -rf sonar-scanner-$RELEASE-linux/jre
    - sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' ./sonar-scanner-$RELEASE-linux/bin/sonar-scanner
    - cp sonar-project.properties ./sonar-scanner-$RELEASE-linux/conf/sonar-scanner.properties
    - sonar-scanner-$RELEASE-linux/bin/sonar-scanner -X
  when:
    branch:
    - develop
    - release/*
    event:
    - push
    - merge

- name: nodejs_build_DEV
  image: node:16.14.0
  commands:
  - cd ./govco-pwa/
  - npm install -g @angular/cli
  - npm i --save-dev @types/select2
  - ng build --prod
  when:
    branch:
    - develop
    event:
    - push
    - merge

- name: nodejs_build_QA
  image: node:16.14.0
  commands:
  - cd ./govco-pwa/
  - npm install -g @angular/cli
  - npm i --save-dev @types/select2
  - ng build --prod
  when:
    branch:
    - stage
    event:
    - push
    - merge

- name: upload_to_aws_s3_dev
  image: plugins/s3
  settings:
    bucket: 
      from_secret: BUCKET
    access_key: 
      from_secret: ACCESS_KEY_S3
    secret_key: 
      from_secret: SECRET_S3
    region:
      from_secret: REGION_S3
    strip_prefix: govco-pwa/dist/govco-pwa
    delete: true
    source: ./govco-pwa/dist/govco-pwa/**/*
    target: /
  when:
    branch:
    - develop
    event:
    - push
    - merge

- name: upload_to_aws_s3_stage
  image: plugins/s3
  settings:
    bucket: 
      from_secret: BUCKET_STAGE
    access_key: 
      from_secret: ACCESS_KEY_S3
    secret_key: 
      from_secret: SECRET_S3
    region:
      from_secret: REGION_S3
    strip_prefix: govco-pwa/dist/govco-pwa
    delete: true
    source: ./govco-pwa/dist/govco-pwa/**/*
    target: /
  when:
    branch:
    - stage
    event:
    - push
    - merge

- name: upload_to_aws_s3_qa_op
  image: plugins/s3
  settings:
    bucket: 
      from_secret: BUCKET_QA_OP
    access_key: 
      from_secret: ACCESS_KEY_S3_QA_OP
    secret_key: 
      from_secret: SECRET_S3_QA_OP
    region:
      from_secret: REGION_S3
    # strip_prefix: govco-pwa/dist/govco-pwa
    strip_prefix: govco-pwa/src
    delete: true
    # source: ./govco-pwa/dist/govco-pwa/**/*
    source: ./govco-pwa/src/favicon.ico
    target: /
  when:
    branch:
    - devops
    event:
    - push
    - merge

- name: upload_to_aws_s3_pre
  image: plugins/s3
  settings:
    bucket: 
      from_secret: BUCKET_PRE
    access_key: 
      from_secret: ACCESS_KEY_S3_PRE
    secret_key: 
      from_secret: SECRET_S3_PRE
    region:
      from_secret: REGION_S3
    # strip_prefix: govco-pwa/dist/govco-pwa
    strip_prefix: govco-pwa/src
    delete: true
    # source: ./govco-pwa/dist/govco-pwa/**/*
    source: ./govco-pwa/src/favicon.ico
    target: /
  when:
    branch:
    - devops
    event:
    - push
    - merge

- name: slack_notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_AND_WEBHOOK
    channel: despliegue-continuo
    link_names: true
    template: >
      {{#if build.pull }}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://gitlab.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
      {{else}}
        *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
      {{/if}}
      *Repo:* {{ repo.name }}
      *Branch:* <http://https://gitlab.com/govco-developers/{{ repo.owner }}/repos/{{ repo.name }}/commits?until=refs/heads/{{ build.branch }}&merges=include|{{ build.branch }}>
      *Commit:* <http://https://gitlab.com/govco-developers/{{ repo.owner }}/repos/{{ repo.name }}/commits/{{ build.commit }}|{{ truncate build.commit 8 }}>

      Author: {{ build.author }}

      <{{ build.link }}|Visit build page ↗>
  when:
    branch:
    - develop
    - release/*
    - master
    - stage
    status:
    - failure
    - success