export const environment = {
  production: true,
  serverUrlHome: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/home",
  serverUrlHomeAdm: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/home",
  apiCrossUrl: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/cross/",
  urlApiFooter: 'https://api-interno.www.gov.co/api/cross/',
  urlApiEntidades: 'https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/entidades',
  serverCategorias: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/categorias-subcategorias/",
  urlApiTramites: "https://aws-api-interno.www.gov.co/api/ficha-tramites-y-servicios",
  //serverUrlNoticias: "https://aws-api-interno.www.gov.co/api/noticias",
  serverUrlNoticias: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/noticias/",
  serverUrlBuscador: "https://prebuscador.www.gov.co/api/v1",
  serverIntegracion: 'https://api-interno.www.gov.co/api/integracion-sedes/IntegracionSedes/',
  severApiCross: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/cross/",
  serverUrl: 'http://100.24.232.62:8085/api/',
  authIssuer: 'https://qaautenticaciondigital.and.gov.co',
  clientID: "GOVCONoticias",
  apiCrossUrl: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/cross/",
  apiNoticiasDetalle: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/noticias/",
  serverCategoriaSubcategoriaUrl: 'https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/categorias-subcategorias/',
  serverEntidades: 'https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/entidades/',

};
