export const environment = {
  production: true,
  serverUrlHome: "http://100.24.232.62:8080/api",
  serverUrlHomeAdm: "http://100.24.232.62:8080/api",
  apiCrossUrl: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/cross/",
  urlApiFooter: 'https://api-interno.www.gov.co/api/cross/',
  urlApiEntidades: 'https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/entidades',
   serverUrlNoticias: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/noticias/",
 // serverUrlNoticias:'http://100.24.232.62:8093/api/noticias/',
  urlApiTramites: "https://aws-api-interno.www.gov.co/api/ficha-tramites-y-servicios",
  serverUrlNoticias: "https://aws-api-interno.www.gov.co/api/noticias",
  serverUrlBuscador: "https://prebuscador.www.gov.co/api/v1",
  serverIntegracion: 'https://api-interno.www.gov.co/api/integracion-sedes/IntegracionSedes/',
  severApiCross: "https://a1u3bqb22e.execute-api.us-east-1.amazonaws.com/qa/api/cross/",
  serverUrl: 'http://100.24.232.62:8085/api/',
  clientID: "GOVCONoticias",
  authIssuer: 'https://qaautenticaciondigital.and.gov.co',
  apiNoticiasDetalle: "http://100.24.232.62:8093/api/",
  serverCategoriaSubcategoriaUrl: 'http://100.24.232.62:8087/api/',
  serverEntidades: 'http://100.24.232.62:8085/api/'
};
