export const urlsLocal = {
    fichaTramite: '/ficha-tramites-y-servicios',
    ficha_tramite_pwa: 'ficha-tramites-y-servicios',
    codigo_ciiu_tramites: 'codigos-ciiu-y-tramites',
    certificados:'consulta-certificados',
    ventanillas:'ventanillas-unicas',
    fichaTramiteId: '/ficha-tramites-y-servicios/T',
    servicios: '/servicios',
    noticias: '/noticias',
    noticiasDetalle: '/noticias/detalle/',
    biblioteca: '/participa',
    entidadesEstado: '/entidades',
    sobreNosotros: '/sobre-nosotros',
    acercaPortal: '/acerca-del-portal',
    serviciosEntidades: '/servicios-para-entidades',
    categorias_subcategorias:'categorias-subcategorias-pwa',
    c_s_mas_consultado:'lo-mas-consultado',
    c_s_tramites_destacados:'tramites-destacados',
    c_s_todos_los_tramites: 'todos-los-tramites',
    c_s_actualidad: 'actualidad',
    buscador: 'buscador',
}
