export const urlsLocal = {
    fichaTramite: '/ficha-tramites-y-servicios',
    ficha_tramite_pwa: 'ficha-tramites-y-servicios',
    codigo_ciiu_tramites: 'codigos-ciiu-y-tramites',
    certificados:'consulta-certificados',
    ventanillas:'ventanillas-unicas',
    fichaTramiteId: '/ficha-tramites-y-servicios/T',
    servicios: '/servicios',
    noticias: '/noticias',
    noticiasDetalle: '/noticias/detalle/',
    biblioteca: '/participa',
    entidadesEstado: '/entidades',
    sobreNosotros: '/sobre-nosotros',
    acercaPortal: '/acerca-del-portal',
    serviciosEntidades: '/servicios-para-entidades',
    categorias_subcategorias:'categorias-subcategorias-pwa',
    buscador: 'buscador',
}
